#!/bin/bash
# ***Run with root privileges using command "sudo bash AUTOINSTALL"***
# This bash script file installs the necessary packages for automated netaccess authentication
# without user intervention.

# Install necessary packages
apt install git
git clone https://github.com/cibinjoseph/IITM-Netaccess-Approval.git netaccess_git
apt install python
apt install python-pip
pip2 install mechanize

# Change netaccess.py to executable 
echo 'Creating temperory netaccess_git directory'
chmod +x netaccess_git/netaccess.py

# Move netaccess to /usr/bin folder for access
cp netaccess_git/netaccess.py /usr/bin

# Remove netaccess_git directory
echo 'Removing unnecessary netaccess_git directory'
rm -r netaccess_git

echo
echo 'INSTALLATION COMPLETED SUCCESSFULLY'
echo
echo '---------------- USAGE ----------------'
echo '1. To run code, use command "netaccess"'
echo '2. To avoid having to input username and password every time the code is executed,'
echo '     enter them directly in the code located at /usr/bin/netaccess.py'
echo '     in the fields "YourUsername" and "YourPassword" in line number 7 and 8.'
echo '     Retain the double quotes.'
echo '3. Leaving the password field unchanged lets you input it during runtime securely.'
echo '---------------------------------------'

