#!/bin/bash
# This bash script file installs the necessary packages for automated netaccess authentication.
# ***Run with root privileges (sudo)***

# Install necessary packages
apt install git
apt install python
apt install python-pip
pip install mechanize

# Change netaccess.py to executable 
chmod +x netaccess.py

# Move netaccess to /usr/bin folder for access
cp netaccess.py /usr/bin
